<?php

$title = 'elearn Courses';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('course', array('action'=>'add'));?>">Add new course</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Teacher</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($courses as $course) : ?>
<tr>
    <td><?php echo $this->escapeHtml($course->name);?></td>
    <td><?php echo $this->escapeHtml($course->teacher);?></td>
    <td>
        <a href="<?php echo $this->url('course',
            array('action'=>'edit', 'id' => $course->id));?>">Edit</a>
        <a href="<?php echo $this->url('course',
            array('action'=>'delete', 'id' => $course->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
